namespace GbaMonoGame.Rayman3.Readvanced;

public enum AchievementId
{
    CompleteWorld1 = 0,
    CompleteWorld2 = 1,
    CompleteWorld3 = 2,
    CompleteWorld4 = 3,
    DefeatBossMachine = 4,
    DefeatBossBadDreams = 5,
    DefeatBossRockAndLava = 6,
    DefeatBossScaleMan = 7,
    DefeatBossFinal = 8,
    CollectAllWorld1 = 9,
    CollectAllWorld2 = 10,
    CollectAllWorld3 = 11,
    CollectAllWorld4 = 12,
    Collect1000thLum = 13,
    CompleteGCNBonus = 14,
    CollectAllLives = 15,
    TimeAttackBronze = 16,
    TimeAttackSilver = 17,
    TimeAttackGold = 18,
    DefeatPirateWithKeg = 19,
    CompleteMarshAwakening1WithoutMoving = 20,
    CompleteMissileRace1WithoutStrafing = 21,
    RideKegBackwards = 22,
    CompleteCaveBadDreamsWithMaxSkullHits = 23,
    CompleteMenhirHillsWithoutDying = 24,
    CompleteFreeFallingWithoutCheckpoint = 25,
    DefeatPirateWithLava = 26,
    DefeatRockyWithoutBlueLum = 27,
    CompleteRockAndLavaWithoutDefeatingBlackLums = 28,
    CompleteMissileRace2WithoutDamage = 29,
    DefeatEveryPirateType = 30,
    MultiplayerWin = 31,
    ViewOriginalMenu = 32,
    Count = 33,
}