namespace GbaMonoGame.Rayman3.Readvanced;

public enum AchievementId
{
    CompleteWorld1 = 0,
    CompleteWorld2 = 1,
    CompleteWorld3 = 2,
    CompleteWorld4 = 3,
    DefeatBossMachine = 4,
    DefeatJano = 5,
    DefeatRocky = 6,
    DefeatScaleman = 7,
    DefeatGrolgoth = 8,
    CollectAllWorld1 = 9,
    CollectAllWorld2 = 10,
    CollectAllWorld3 = 11,
    CollectAllWorld4 = 12,
    Collect1000thLum = 13,
    CompleteGCNBonus = 14,
    CollectAllLives = 15,
    TimeAttackBronze = 16,
    TimeAttackSilver = 17,
    TimeAttackGold = 18,
    DefeatPirateWithKeg = 19,
    CompleteMarshes1WithoutMoving = 20,
    RideKegBackwards = 21,
    CompleteCaveBadDreamsWithMaxSkullHits = 22,
    CompleteMenhirHillsWithoutDying = 23,
    CompleteFreeFallingWithoutCheckpoint = 24,
    DefeatPirateWithLava = 25,
    DefeatRockyWithoutBlueLum = 26,
    CompleteRockAndLavaWithoutDefeatingBlackLums = 27,
    CompleteMissileRace2WithoutDamage = 28,
    DefeatPirateOfEveryRank = 29,
    ViewOriginalMenu = 30,
    Count = 31,
}