namespace GbaMonoGame.Rayman3.J2me;

// NOTE: All resources are packed in alphabetical order
public partial class Game
{
    public const int ARCHIVE_INDEX_ANIM = 0x00;
    public const int ARCHIVE_INDEX_IMG  = 0x01;
    public const int ARCHIVE_INDEX_MAP  = 0x02;

    public readonly ResourceId RESOURCE_ID_DATA_ACTOR_TYPES             = new(0x00, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000100
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_BLUE_LUM           = new(0x01, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000101
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_BOMB               = new(0x02, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000102
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_BULLET             = new(0x03, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000103
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_CAGE               = new(0x04, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000104
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_FIST               = new(0x05, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000105
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_FLY                = new(0x06, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000106
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_FONT               = new(0x07, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000107
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_GREEN_LUM          = new(0x08, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000108
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_JUNGLE_PLATFORM    = new(0x09, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000109
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_LAVA_BUBBLE        = new(0x0A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010A
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_LAVA_PLATFORM      = new(0x0B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010B
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_LEVEL_POST         = new(0x0C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010C
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_LEVEL_SIGN         = new(0x0D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010D
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_OURSIN             = new(0x0E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010E
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_PIRATE             = new(0x0F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010F
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_RAYMAN             = new(0x10, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000110
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_RED_LUM            = new(0x11, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000111
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_SPIKE              = new(0x12, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000112
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_SWING              = new(0x13, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000113
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_TENTACLE           = new(0x14, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000114
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_WHITE_LUM          = new(0x15, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000115
    public readonly ResourceId RESOURCE_ID_DATA_ANIM_YELLOW_LUM         = new(0x16, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000116
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_CAGE_BREAK        = new(0x17, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000117
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_CAGE_HIT          = new(0x18, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000118
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_ENEMY_DEATH       = new(0x19, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000119
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_ENEMY_HIT         = new(0x1A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011A
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_ENTER_LEVEL       = new(0x1B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011B
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_LUMS              = new(0x1C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011C
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_LUMS_RED          = new(0x1D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011D
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_LUMS_WHITE        = new(0x1E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011E
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_MENU_MOVE         = new(0x1F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011F
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_MENU_SELECT       = new(0x20, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000120
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_MUSIC_GAMEOVER    = new(0x21, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000121
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_MUSIC_LEVELDONE   = new(0x22, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000122
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_MUSIC_MAP         = new(0x23, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000123
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_MUSIC_SPLASH      = new(0x24, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000124
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_PUNCH_CHARGE      = new(0x25, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000125
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_PUNCH_RELEASED    = new(0x26, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000126
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_RAYMAN_CROUCH     = new(0x27, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000127
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_RAYMAN_DEATH      = new(0x28, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000128
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_RAYMAN_HELICO     = new(0x29, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000129
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_RAYMAN_HIT        = new(0x2A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012A
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_RAYMAN_JUMP       = new(0x2B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012B
    public readonly ResourceId RESOURCE_ID_DATA_SOUND_RAYMAN_WATER      = new(0x2C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012C
    public readonly ResourceId RESOURCE_ID_DATA_TEXTBANK_GAME           = new(0x2D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012D
    public readonly ResourceId RESOURCE_ID_DATA_TEXTBANK_CREDITS_UNUSED = new(0x2E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012E
    public readonly ResourceId RESOURCE_ID_DATA_TEXTBANK_CREDITS        = new(0x2F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012F
    public readonly ResourceId RESOURCE_ID_DATA_TEXTBANK_HELP           = new(0x30, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000130

    public readonly ResourceId RESOURCE_ID_IMG_TILES_JUNGLE             = new(0x00, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000400
    public readonly ResourceId RESOURCE_ID_IMG_TILES_LAVA               = new(0x01, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000401
    public readonly ResourceId RESOURCE_ID_IMG_BULLETS                  = new(0x02, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000402
    public readonly ResourceId RESOURCE_ID_IMG_CAGE                     = new(0x03, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000403
    public readonly ResourceId RESOURCE_ID_IMG_FLY                      = new(0x04, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000404
    public readonly ResourceId RESOURCE_ID_IMG_FONT                     = new(0x05, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000405
    public readonly ResourceId RESOURCE_ID_IMG_JUNGLE_PLATFORM          = new(0x06, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000406
    public readonly ResourceId RESOURCE_ID_IMG_LAVA_BUBBLE              = new(0x07, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000407
    public readonly ResourceId RESOURCE_ID_IMG_LAVA_PLATFORM            = new(0x08, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000408
    public readonly ResourceId RESOURCE_ID_IMG_LEVEL_POST               = new(0x09, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000409
    public readonly ResourceId RESOURCE_ID_IMG_LEVEL_SIGN               = new(0x0A, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040A
    public readonly ResourceId RESOURCE_ID_IMG_LUMS                     = new(0x0B, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040B
    public readonly ResourceId RESOURCE_ID_IMG_OURSIN                   = new(0x0C, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040C
    public readonly ResourceId RESOURCE_ID_IMG_PIRATE                   = new(0x0D, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040D
    public readonly ResourceId RESOURCE_ID_IMG_RAYMAN                   = new(0x0E, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040E
    public readonly ResourceId RESOURCE_ID_IMG_TENTACLE                 = new(0x0F, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040F
    public readonly ResourceId RESOURCE_ID_IMG_GAMELOFT_COPYRIGHT       = new(0x10, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000410
    public readonly ResourceId RESOURCE_ID_IMG_GAMELOFT_LOGO            = new(0x11, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000411
    public readonly ResourceId RESOURCE_ID_IMG_SPLASH_SCREEN            = new(0x12, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000412
    public readonly ResourceId RESOURCE_ID_IMG_TILES_JUNGLE_UNUSED      = new(0x13, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000413
    public readonly ResourceId RESOURCE_ID_IMG_TILES_LAVA_UNUSED        = new(0x14, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000414

    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_1      = new(0x00, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000900
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_2      = new(0x01, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000901
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_3      = new(0x02, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000902
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_4      = new(0x03, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000903
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_5      = new(0x04, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000904
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_6      = new(0x05, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000905
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_7      = new(0x06, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000906
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_LEVEL_8      = new(0x07, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000907
    public readonly ResourceId RESOURCE_ID_DATA_BACKGROUND_WORLDMAP     = new(0x08, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000908
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_1           = new(0x09, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000909
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_2           = new(0x0A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090A
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_3           = new(0x0B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090B
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_4           = new(0x0C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090C
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_5           = new(0x0D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090D
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_6           = new(0x0E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090E
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_7           = new(0x0F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090F
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_8           = new(0x10, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000910
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_LEVEL_9           = new(0x11, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000911
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_WORLDMAP          = new(0x12, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000912
    public readonly ResourceId RESOURCE_ID_DATA_SCENE_MAP               = new(0x13, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000913
    public readonly ResourceId RESOURCE_ID_DATA_SLOPE_DISPLACEMENTS     = new(0x14, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000914

    public const int TEXTBANK_INDEX_GAME           = 0x2D;
    public const int TEXTBANK_INDEX_CREDITS_UNUSED = 0x2E;
    public const int TEXTBANK_INDEX_CREDITS        = 0x2F;
    public const int TEXTBANK_INDEX_HELP           = 0x30;

    public readonly StringId STRING_ID_NEW_GAME              = new(0x00, TEXTBANK_INDEX_GAME); // New Game
    public readonly StringId STRING_ID_CONTINUE              = new(0x09, TEXTBANK_INDEX_GAME); // Continue
    public readonly StringId STRING_ID_ABOUT                 = new(0x12, TEXTBANK_INDEX_GAME); // About
    public readonly StringId STRING_ID_HELP                  = new(0x18, TEXTBANK_INDEX_GAME); // Help
    public readonly StringId STRING_ID_HELP_TITLE            = new(0x1D, TEXTBANK_INDEX_GAME); // HELP
    public readonly StringId STRING_ID_RESUME                = new(0x22, TEXTBANK_INDEX_GAME); // Resume
    public readonly StringId STRING_ID_RESTART               = new(0x29, TEXTBANK_INDEX_GAME); // Restart
    public readonly StringId STRING_ID_MUSIC_HIGH            = new(0x31, TEXTBANK_INDEX_GAME); // Music : High
    public readonly StringId STRING_ID_MUSIC_MEDIUM          = new(0x3E, TEXTBANK_INDEX_GAME); // Music : Medium
    public readonly StringId STRING_ID_MUSIC_LOW             = new(0x4D, TEXTBANK_INDEX_GAME); // Music : Low
    public readonly StringId STRING_ID_MUSIC_OFF             = new(0x59, TEXTBANK_INDEX_GAME); // Music : Off
    public readonly StringId STRING_ID_MAIN_MENU             = new(0x65, TEXTBANK_INDEX_GAME); // Main Menu
    public readonly StringId STRING_ID_EXIT                  = new(0x6F, TEXTBANK_INDEX_GAME); // Exit
    public readonly StringId STRING_ID_ENTER_NOW             = new(0x74, TEXTBANK_INDEX_GAME); // Enter Now!
    public readonly StringId STRING_ID_LEVEL                 = new(0x7F, TEXTBANK_INDEX_GAME); // Level 
    public readonly StringId STRING_ID_UNKNOWN_STATUS        = new(0x86, TEXTBANK_INDEX_GAME); //  ?/?
    public readonly StringId STRING_ID_LOADING               = new(0x8B, TEXTBANK_INDEX_GAME); // Loading
    public readonly StringId STRING_ID_LEVEL_DONE            = new(0x93, TEXTBANK_INDEX_GAME); // LEVEL DONE
    public readonly StringId STRING_ID_GAME_OVER             = new(0x9E, TEXTBANK_INDEX_GAME); // GAME OVER
    public readonly StringId STRING_ID_VICTORY               = new(0xA8, TEXTBANK_INDEX_GAME); // VICTORY !!!
    public readonly StringId STRING_ID_ENABLE_SOUND          = new(0xB4, TEXTBANK_INDEX_GAME); // ENABLE SOUND?
    public readonly StringId STRING_ID_EMPTY                 = new(0xC2, TEXTBANK_INDEX_GAME); // 
    public readonly StringId STRING_ID_YES                   = new(0xC3, TEXTBANK_INDEX_GAME); // yes
    public readonly StringId STRING_ID_NO                    = new(0xC7, TEXTBANK_INDEX_GAME); // no
    public readonly StringId STRING_ID_EXIT_QUESTION         = new(0xCA, TEXTBANK_INDEX_GAME); // Exit?
    public readonly StringId STRING_ID_RESTART_QUESTION      = new(0xD0, TEXTBANK_INDEX_GAME); // Restart?
    public readonly StringId STRING_ID_TO_MAIN_MENU_QUESTION = new(0xD9, TEXTBANK_INDEX_GAME); // To Main menu?

    public readonly StringId STRING_ID_SUPPORT_MAIL          = new(0x46, TEXTBANK_INDEX_CREDITS); // support mail
    public readonly StringId STRING_ID_VERSION_NUMBER        = new(0x9B, TEXTBANK_INDEX_CREDITS); // Version Number

    public readonly StringId STRING_ID_5_LAUNCH_THE_FIST     = new(0xB7, TEXTBANK_INDEX_HELP); // 5 : launch the fist
}