namespace GbaMonoGame.Rayman3.J2ME;

// NOTE: All resources are packed in alphabetical order
public partial class Game
{
    public const int ARCHIVE_INDEX_ANIM = 0x00;
    public const int ARCHIVE_INDEX_IMG  = 0x01;
    public const int ARCHIVE_INDEX_MAP  = 0x02;

    public readonly int RESOURCE_ID_DATA_ACTOR_TYPES             = ResourceId.Create(0x00, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000100
    public readonly int RESOURCE_ID_DATA_ANIM_BLUE_LUM           = ResourceId.Create(0x01, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000101
    public readonly int RESOURCE_ID_DATA_ANIM_BOMB               = ResourceId.Create(0x02, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000102
    public readonly int RESOURCE_ID_DATA_ANIM_BULLET             = ResourceId.Create(0x03, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000103
    public readonly int RESOURCE_ID_DATA_ANIM_CAGE               = ResourceId.Create(0x04, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000104
    public readonly int RESOURCE_ID_DATA_ANIM_FIST               = ResourceId.Create(0x05, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000105
    public readonly int RESOURCE_ID_DATA_ANIM_FLY                = ResourceId.Create(0x06, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000106
    public readonly int RESOURCE_ID_DATA_ANIM_FONT               = ResourceId.Create(0x07, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000107
    public readonly int RESOURCE_ID_DATA_ANIM_GREEN_LUM          = ResourceId.Create(0x08, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000108
    public readonly int RESOURCE_ID_DATA_ANIM_JUNGLE_PLATFORM    = ResourceId.Create(0x09, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000109
    public readonly int RESOURCE_ID_DATA_ANIM_LAVA_BUBBLE        = ResourceId.Create(0x0A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010A
    public readonly int RESOURCE_ID_DATA_ANIM_LAVA_PLATFORM      = ResourceId.Create(0x0B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010B
    public readonly int RESOURCE_ID_DATA_ANIM_LEVEL_POST         = ResourceId.Create(0x0C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010C
    public readonly int RESOURCE_ID_DATA_ANIM_LEVEL_SIGN         = ResourceId.Create(0x0D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010D
    public readonly int RESOURCE_ID_DATA_ANIM_OURSIN             = ResourceId.Create(0x0E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010E
    public readonly int RESOURCE_ID_DATA_ANIM_PIRATE             = ResourceId.Create(0x0F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000010F
    public readonly int RESOURCE_ID_DATA_ANIM_RAYMAN             = ResourceId.Create(0x10, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000110
    public readonly int RESOURCE_ID_DATA_ANIM_RED_LUM            = ResourceId.Create(0x11, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000111
    public readonly int RESOURCE_ID_DATA_ANIM_SPIKE              = ResourceId.Create(0x12, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000112
    public readonly int RESOURCE_ID_DATA_ANIM_SWING              = ResourceId.Create(0x13, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000113
    public readonly int RESOURCE_ID_DATA_ANIM_TENTACLE           = ResourceId.Create(0x14, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000114
    public readonly int RESOURCE_ID_DATA_ANIM_WHITE_LUM          = ResourceId.Create(0x15, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000115
    public readonly int RESOURCE_ID_DATA_ANIM_YELLOW_LUM         = ResourceId.Create(0x16, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000116
    public readonly int RESOURCE_ID_DATA_SOUND_CAGE_BREAK        = ResourceId.Create(0x17, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000117
    public readonly int RESOURCE_ID_DATA_SOUND_CAGE_HIT          = ResourceId.Create(0x18, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000118
    public readonly int RESOURCE_ID_DATA_SOUND_ENEMY_DEATH       = ResourceId.Create(0x19, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000119
    public readonly int RESOURCE_ID_DATA_SOUND_ENEMY_HIT         = ResourceId.Create(0x1A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011A
    public readonly int RESOURCE_ID_DATA_SOUND_ENTER_LEVEL       = ResourceId.Create(0x1B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011B
    public readonly int RESOURCE_ID_DATA_SOUND_LUMS              = ResourceId.Create(0x1C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011C
    public readonly int RESOURCE_ID_DATA_SOUND_LUMS_RED          = ResourceId.Create(0x1D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011D
    public readonly int RESOURCE_ID_DATA_SOUND_LUMS_WHITE        = ResourceId.Create(0x1E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011E
    public readonly int RESOURCE_ID_DATA_SOUND_MENU_MOVE         = ResourceId.Create(0x1F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000011F
    public readonly int RESOURCE_ID_DATA_SOUND_MENU_SELECT       = ResourceId.Create(0x20, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000120
    public readonly int RESOURCE_ID_DATA_SOUND_MUSIC_GAMEOVER    = ResourceId.Create(0x21, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000121
    public readonly int RESOURCE_ID_DATA_SOUND_MUSIC_LEVELDONE   = ResourceId.Create(0x22, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000122
    public readonly int RESOURCE_ID_DATA_SOUND_MUSIC_MAP         = ResourceId.Create(0x23, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000123
    public readonly int RESOURCE_ID_DATA_SOUND_MUSIC_SPLASH      = ResourceId.Create(0x24, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000124
    public readonly int RESOURCE_ID_DATA_SOUND_PUNCH_CHARGE      = ResourceId.Create(0x25, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000125
    public readonly int RESOURCE_ID_DATA_SOUND_PUNCH_RELEASED    = ResourceId.Create(0x26, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000126
    public readonly int RESOURCE_ID_DATA_SOUND_RAYMAN_CROUCH     = ResourceId.Create(0x27, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000127
    public readonly int RESOURCE_ID_DATA_SOUND_RAYMAN_DEATH      = ResourceId.Create(0x28, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000128
    public readonly int RESOURCE_ID_DATA_SOUND_RAYMAN_HELICO     = ResourceId.Create(0x29, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000129
    public readonly int RESOURCE_ID_DATA_SOUND_RAYMAN_HIT        = ResourceId.Create(0x2A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012A
    public readonly int RESOURCE_ID_DATA_SOUND_RAYMAN_JUMP       = ResourceId.Create(0x2B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012B
    public readonly int RESOURCE_ID_DATA_SOUND_RAYMAN_WATER      = ResourceId.Create(0x2C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012C
    public readonly int RESOURCE_ID_DATA_TEXTBANK_GAME           = ResourceId.Create(0x2D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012D
    public readonly int RESOURCE_ID_DATA_TEXTBANK_CREDITS_UNUSED = ResourceId.Create(0x2E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012E
    public readonly int RESOURCE_ID_DATA_TEXTBANK_CREDITS        = ResourceId.Create(0x2F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x6000012F
    public readonly int RESOURCE_ID_DATA_TEXTBANK_HELP           = ResourceId.Create(0x30, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_ANIM); // 0x60000130

    public readonly int RESOURCE_ID_IMG_TILES_JUNGLE             = ResourceId.Create(0x00, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000400
    public readonly int RESOURCE_ID_IMG_TILES_LAVA               = ResourceId.Create(0x01, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000401
    public readonly int RESOURCE_ID_IMG_BULLETS                  = ResourceId.Create(0x02, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000402
    public readonly int RESOURCE_ID_IMG_CAGE                     = ResourceId.Create(0x03, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000403
    public readonly int RESOURCE_ID_IMG_FLY                      = ResourceId.Create(0x04, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000404
    public readonly int RESOURCE_ID_IMG_FONT                     = ResourceId.Create(0x05, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000405
    public readonly int RESOURCE_ID_IMG_JUNGLE_PLATFORM          = ResourceId.Create(0x06, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000406
    public readonly int RESOURCE_ID_IMG_LAVA_BUBBLE              = ResourceId.Create(0x07, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000407
    public readonly int RESOURCE_ID_IMG_LAVA_PLATFORM            = ResourceId.Create(0x08, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000408
    public readonly int RESOURCE_ID_IMG_LEVEL_POST               = ResourceId.Create(0x09, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000409
    public readonly int RESOURCE_ID_IMG_LEVEL_SIGN               = ResourceId.Create(0x0A, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040A
    public readonly int RESOURCE_ID_IMG_LUMS                     = ResourceId.Create(0x0B, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040B
    public readonly int RESOURCE_ID_IMG_OURSIN                   = ResourceId.Create(0x0C, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040C
    public readonly int RESOURCE_ID_IMG_PIRATE                   = ResourceId.Create(0x0D, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040D
    public readonly int RESOURCE_ID_IMG_RAYMAN                   = ResourceId.Create(0x0E, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040E
    public readonly int RESOURCE_ID_IMG_TENTACLE                 = ResourceId.Create(0x0F, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x6000040F
    public readonly int RESOURCE_ID_IMG_GAMELOFT_COPYRIGHT       = ResourceId.Create(0x10, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000410
    public readonly int RESOURCE_ID_IMG_GAMELOFT_LOGO            = ResourceId.Create(0x11, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000411
    public readonly int RESOURCE_ID_IMG_SPLASH_SCREEN            = ResourceId.Create(0x12, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000412
    public readonly int RESOURCE_ID_IMG_TILES_JUNGLE_UNUSED      = ResourceId.Create(0x13, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000413
    public readonly int RESOURCE_ID_IMG_TILES_LAVA_UNUSED        = ResourceId.Create(0x14, RESOURCE_TYPE.IMAGE, ARCHIVE_INDEX_IMG); // 0x60000414

    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_1      = ResourceId.Create(0x00, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000900
    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_2      = ResourceId.Create(0x01, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000901
    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_3      = ResourceId.Create(0x02, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000902
    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_4      = ResourceId.Create(0x03, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000903
    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_5      = ResourceId.Create(0x04, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000904
    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_6      = ResourceId.Create(0x05, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000905
    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_7      = ResourceId.Create(0x06, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000906
    public readonly int RESOURCE_ID_DATA_BACKGROUND_LEVEL_8      = ResourceId.Create(0x07, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000907
    public readonly int RESOURCE_ID_DATA_BACKGROUND_WORLDMAP     = ResourceId.Create(0x08, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000908
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_1           = ResourceId.Create(0x09, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000909
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_2           = ResourceId.Create(0x0A, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090A
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_3           = ResourceId.Create(0x0B, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090B
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_4           = ResourceId.Create(0x0C, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090C
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_5           = ResourceId.Create(0x0D, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090D
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_6           = ResourceId.Create(0x0E, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090E
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_7           = ResourceId.Create(0x0F, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x6000090F
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_8           = ResourceId.Create(0x10, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000910
    public readonly int RESOURCE_ID_DATA_SCENE_LEVEL_9           = ResourceId.Create(0x11, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000911
    public readonly int RESOURCE_ID_DATA_SCENE_WORLDMAP          = ResourceId.Create(0x12, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000912
    public readonly int RESOURCE_ID_DATA_SCENE_MAP               = ResourceId.Create(0x13, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000913
    public readonly int RESOURCE_ID_DATA_SLOPE_DISPLACEMENTS     = ResourceId.Create(0x14, RESOURCE_TYPE.DATA, ARCHIVE_INDEX_MAP); // 0x60000914

    public const int TEXTBANK_INDEX_GAME           = 0x2D;
    public const int TEXTBANK_INDEX_CREDITS_UNUSED = 0x2E;
    public const int TEXTBANK_INDEX_CREDITS        = 0x2F;
    public const int TEXTBANK_INDEX_HELP           = 0x30;

    public readonly int STRING_ID_NEW_GAME              = StringId.Create(0x00, TEXTBANK_INDEX_GAME); // New Game
    public readonly int STRING_ID_CONTINUE              = StringId.Create(0x09, TEXTBANK_INDEX_GAME); // Continue
    public readonly int STRING_ID_ABOUT                 = StringId.Create(0x12, TEXTBANK_INDEX_GAME); // About
    public readonly int STRING_ID_HELP                  = StringId.Create(0x18, TEXTBANK_INDEX_GAME); // Help
    public readonly int STRING_ID_HELP_TITLE            = StringId.Create(0x1D, TEXTBANK_INDEX_GAME); // HELP
    public readonly int STRING_ID_RESUME                = StringId.Create(0x22, TEXTBANK_INDEX_GAME); // Resume
    public readonly int STRING_ID_RESTART               = StringId.Create(0x29, TEXTBANK_INDEX_GAME); // Restart
    public readonly int STRING_ID_MUSIC_HIGH            = StringId.Create(0x31, TEXTBANK_INDEX_GAME); // Music : High
    public readonly int STRING_ID_MUSIC_MEDIUM          = StringId.Create(0x3E, TEXTBANK_INDEX_GAME); // Music : Medium
    public readonly int STRING_ID_MUSIC_LOW             = StringId.Create(0x4D, TEXTBANK_INDEX_GAME); // Music : Low
    public readonly int STRING_ID_MUSIC_OFF             = StringId.Create(0x59, TEXTBANK_INDEX_GAME); // Music : Off
    public readonly int STRING_ID_MAIN_MENU             = StringId.Create(0x65, TEXTBANK_INDEX_GAME); // Main Menu
    public readonly int STRING_ID_EXIT                  = StringId.Create(0x6F, TEXTBANK_INDEX_GAME); // Exit
    public readonly int STRING_ID_ENTER_NOW             = StringId.Create(0x74, TEXTBANK_INDEX_GAME); // Enter Now!
    public readonly int STRING_ID_LEVEL                 = StringId.Create(0x7F, TEXTBANK_INDEX_GAME); // Level 
    public readonly int STRING_ID_UNKNOWN_STATUS        = StringId.Create(0x86, TEXTBANK_INDEX_GAME); //  ?/?
    public readonly int STRING_ID_LOADING               = StringId.Create(0x8B, TEXTBANK_INDEX_GAME); // Loading
    public readonly int STRING_ID_LEVEL_DONE            = StringId.Create(0x93, TEXTBANK_INDEX_GAME); // LEVEL DONE
    public readonly int STRING_ID_GAME_OVER             = StringId.Create(0x9E, TEXTBANK_INDEX_GAME); // GAME OVER
    public readonly int STRING_ID_VICTORY               = StringId.Create(0xA8, TEXTBANK_INDEX_GAME); // VICTORY !!!
    public readonly int STRING_ID_ENABLE_SOUND          = StringId.Create(0xB4, TEXTBANK_INDEX_GAME); // ENABLE SOUND?
    public readonly int STRING_ID_EMPTY                 = StringId.Create(0xC2, TEXTBANK_INDEX_GAME); // 
    public readonly int STRING_ID_YES                   = StringId.Create(0xC3, TEXTBANK_INDEX_GAME); // yes
    public readonly int STRING_ID_NO                    = StringId.Create(0xC7, TEXTBANK_INDEX_GAME); // no
    public readonly int STRING_ID_EXIT_QUESTION         = StringId.Create(0xCA, TEXTBANK_INDEX_GAME); // Exit?
    public readonly int STRING_ID_RESTART_QUESTION      = StringId.Create(0xD0, TEXTBANK_INDEX_GAME); // Restart?
    public readonly int STRING_ID_TO_MAIN_MENU_QUESTION = StringId.Create(0xD9, TEXTBANK_INDEX_GAME); // To Main menu?

    public readonly int STRING_ID_SUPPORT_MAIL          = StringId.Create(0x46, TEXTBANK_INDEX_CREDITS); // support mail
    public readonly int STRING_ID_VERSION_NUMBER        = StringId.Create(0x9B, TEXTBANK_INDEX_CREDITS); // Version Number

    public readonly int STRING_ID_5_LAUNCH_THE_FIST     = StringId.Create(0xB7, TEXTBANK_INDEX_HELP); // 5 : launch the fist
}