namespace GbaMonoGame.Rayman3.J2ME;

public enum MM_TYPE : sbyte
{
    RESET = 0,
    USE_CONSTANT_SPEED = 1,
    NONE = 2,
    SET_SPEED_XY = 3,
    SET_SPEED_X_RESET_SPEED_Y = 4,
    SET_SPEED_Y_RESET_SPEED_X = 5,
    SET_SPEED_X = 6,
    SET_SPEED_Y = 7,
    SET_ACCELERATION_XY_SET_TARGET_SPEED_XY = 8,
    SET_ACCELERATION_X_SET_TARGET_SPEED_X = 9,
    SET_ACCELERATION_Y_SET_TARGET_SPEED_Y = 10,
    SET_SPEED_XY_SET_ACCELERATION_XY_SET_TARGET_SPEED_XY = 11,
    SET_SPEED_X_SET_ACCELERATION_X_SET_TARGET_SPEED_X = 12,
    SET_SPEED_Y_SET_ACCELERATION_Y_SET_TARGET_SPEED_Y = 13,
}