namespace GbaMonoGame.Rayman3.J2ME;

public enum PHB_TYPE : sbyte
{
    NONE = 0,
    SOLID = 1,
    SOLID_HALF = 2,

    SOLID_ANGLE_90_LEFT = 4,
    SOLID_ANGLE_90_RIGHT = 5,
    SOLID_ANGLE_30_LEFT_1 = 6,
    SOLID_ANGLE_30_LEFT_2 = 7,
    SOLID_ANGLE_30_RIGHT_1 = 8,
    SOLID_ANGLE_30_RIGHT_2 = 9,

    CLIMB = 16,
    DAMAGE = 17,
    INSTA_KILL = 18,

    MOVING_PLATFORM_RIGHT = 20,
    MOVING_PLATFORM_LEFT = 21,
    MOVING_PLATFORM_UP = 22,
    MOVING_PLATFORM_DOWN = 23,
    MOVING_PLATFORM_UP_RIGHT = 24,
    MOVING_PLATFORM_UP_LEFT = 25,
    MOVING_PLATFORM_DOWN_RIGHT = 26,
    MOVING_PLATFORM_DOWN_LEFT = 27,
    MOVING_PLATFORM_STOP = 28,
    WATER = 29,
    HANG_ROOF = 30,
    HANG = 31,
}