namespace GbaMonoGame.Rayman3;

public partial class Grolgoth
{
    public new Action ActionId
    {
        get => (Action)base.ActionId;
        set => base.ActionId = (int)value;
    }

    // TODO: Name
    public enum Action
    {
        Ground_Idle_Right = 0,
        Ground_Idle_Left = 1,
        Action2 = 2,
        Action3 = 3,
        Action4 = 4,
        Action5 = 5,
        Ground_BeginDeployBomb_Right = 6,
        Ground_BeginDeployBomb_Left = 7,
        Ground_DeployBomb_Right = 8,
        Ground_DeployBomb_Left = 9,
        Ground_Hit1_Right = 10,
        Ground_Hit1_Left = 11,
        Ground_Hit2_Right = 12,
        Ground_Hit2_Left = 13,
        Ground_Hit3_Right = 14,
        Ground_Hit3_Left = 15,
        Ground_Hit4_Right = 16,
        Ground_Hit4_Left = 17,
        Ground_PrepareFlyUp_Right = 18,
        Ground_PrepareFlyUp_Left = 19,
        Ground_Land_Right = 20,
        Ground_Land_Left = 21,
        Action22 = 22,
        Action23 = 23,
        Action24 = 24,
        Action25 = 25,
        Action26 = 26,
        Action27 = 27,
        Action28 = 28,
        Action29 = 29,
        Action30 = 30,
        Action31 = 31,
        Action32 = 32,
        Action33 = 33,
        Action34 = 34,
        Action35 = 35,
        Action36 = 36,
        Ground_FallDown_Right = 37,
        Ground_FallDown_Left = 38,
        Ground_FlyUp_Right = 39,
        Ground_FlyUp_Left = 40,
        Ground_ShootLasers_Right = 41,
        Ground_ShootLasers_Left = 42,
        Ground_BeginShootLasers_Right = 43,
        Ground_BeginShootLasers_Left = 44,
        Ground_EndShootLasers_Right = 45,
        Ground_EndShootLasers_Left = 46,
        Ground_BeginShootEnergyShotsHigh_Right = 47,
        Ground_BeginShootEnergyShotsHigh_Left = 48,
        Ground_ShootEnergyShotsHigh_Right = 49,
        Ground_ShootEnergyShotsHigh_Left = 50,
        Ground_BeginShootEnergyShotsLow_Right = 51,
        Ground_BeginShootEnergyShotsLow_Left = 52,
        Ground_ShootEnergyShotsLow_Right = 53,
        Ground_ShootEnergyShotsLow_Left = 54,
        Action55 = 55,
        Action56 = 56,
        Action57 = 57,
        Action58 = 58,
        Action59 = 59,
        Action60 = 60,
        Action61 = 61,
        Action62 = 62,
        Action63 = 63,
        Action64 = 64,
        Action65 = 65,
        Action66 = 66,
        Action67 = 67,
    }
}