namespace GbaMonoGame;

public enum Rayman3Input
{
    MenuUp,
    MenuDown,
    MenuLeft,
    MenuRight,
    MenuLeftExt,
    MenuRightExt,
    MenuConfirm,
    MenuBack,
    MenuLostMultiplayerConnectionBack,
    MenuMultiplayerStart,
    PauseMenuBack,
    GameCubeMenuConfirm,
    GameCubeMenuBack,
    LevelSelectMenuConfirm,
    LevelSelectMenuBack,
    StorySkip,
    StoryNext,
    TextBoxSkip,
    TextBoxNext,
    CreditsSkip,
    Pause,
    GameOverContinue,
    IntroSkip,
    ActorUp,
    ActorDown,
    ActorLeft,
    ActorRight,
    ActorJump,
    ActorAttack,
    ActorSpecialLeft,
    ActorSpecialRight,
}